const GROUPS={
"🔥 Big 3":["One Piece","Naruto","Bleach"],
"⚡ New Gen":["Jujutsu Kaisen","Demon Slayer","My Hero Academia"],
"👑 Classics":["Dragon Ball","Attack on Titan"]
};
const A={
"One Piece":[["Who is the captain of the Straw Hat Pirates?",["Luffy","Zoro","Shanks","Ace"]],["What is Luffy's dream?",["Become Pirate King","Become Marine Admiral","Find All Blue","Become a Yonko"]],["What is Luffy's Devil Fruit power?",["Gum-Gum","Flame-Flame","Dark-Dark","Light-Light"]],["Who is the swordsman of the Straw Hats?",["Zoro","Sanji","Usopp","Franky"]],["Who gave Luffy his straw hat?",["Shanks","Roger","Garp","Rayleigh"]],["What is the name of the world government?",["World Government","Soul Society","Hero Association","Hunter Exam"]],["Who is the navigator of the crew?",["Nami","Robin","Vivi","Perona"]],["What is Sanji's fighting style mainly?",["Kicks","Sword","Fists","Guns"]],["Who is the archaeologist of the Straw Hats?",["Robin","Nami","Boa","Tashigi"]],["What treasure does everyone seek?",["One Piece","Dragon Balls","Death Note","Founding Titan"]]],
"Naruto":[["What village is Naruto from?",["Hidden Leaf","Hidden Sand","Hidden Mist","Hidden Cloud"]],["What is Naruto's signature technique?",["Rasengan","Getsuga Tensho","Bankai","Detroit Smash"]],["Who is Naruto's rival?",["Sasuke","Kiba","Shikamaru","Neji"]],["Who leads Team 7?",["Kakashi","Jiraiya","Iruka","Guy"]],["What beast is sealed inside Naruto?",["Nine-Tails","Eight-Tails","One-Tail","Ten-Tails"]],["What eye technique does Sasuke use?",["Sharingan","Byakugan","Rinnegan only","Geass"]],["Who trained Naruto in Sage Mode?",["Jiraiya","Kakashi","Orochimaru","Tsunade"]],["What clan is Hinata from?",["Hyuga","Uchiha","Nara","Uzumaki"]],["Who becomes the Seventh Hokage?",["Naruto","Sasuke","Kakashi","Shikamaru"]],["What is Naruto's famous catchphrase?",["Believe it!","I'm gonna be King!","Plus Ultra!","Bankai!"]]],
"Bleach":[["Who is the main hero?",["Ichigo","Renji","Urahara","Byakuya"]],["What is Ichigo's sword called?",["Zangetsu","Samehada","Enma","Nichirin"]],["What are Soul Reapers called in Japanese?",["Shinigami","Hollows","Quincy","Arrancar"]],["Who is Ichigo's substitute soul reaper mentor?",["Rukia","Orihime","Yoruichi","Soi Fon"]],["What world do Soul Reapers protect?",["Soul Society","Grand Line","Hidden Leaf","Paradis"]],["What are spirit monsters called?",["Hollows","Titans","Demons","Nomu"]],["Who is known for the Benihime zanpakuto?",["Urahara","Kenpachi","Toshiro","Aizen"]],["What is a Bankai?",["Advanced Zanpakuto release","Ninja technique","Devil Fruit","Hero costume"]],["Who is a Quincy?",["Uryu Ishida","Kon","Chad","Renji"]],["What is Ichigo's main goal?",["Protect his friends","Become Hokage","Find One Piece","Become Hero #1"]]],
"Jujutsu Kaisen":[["Who is the strongest modern sorcerer?",["Gojo","Nanami","Todo","Megumi"]],["What is Yuji's role?",["Sukuna's vessel","Hokage","Hashira","Soul Reaper"]],["What is Gojo's inherited technique?",["Limitless","Sharingan","Nen","Breathing"]],["Who is the King of Curses?",["Sukuna","Mahito","Geto","Jogo"]],["What school does Yuji attend?",["Tokyo Jujutsu High","UA High","Ninja Academy","Soul Society"]],["What is Megumi's technique based on?",["Ten Shadows","Eight Gates","Alchemy","Nen"]],["Who uses Straw Doll Technique?",["Nobara","Maki","Miwa","Shoko"]],["What are cursed spirits born from?",["Negative human emotions","Devil Fruits","Dragon Balls","Titan serum"]],["Who was Gojo's best friend in his student days?",["Geto","Nanami","Toji","Yaga"]],["What does Domain Expansion create?",["A guaranteed-hit domain","A new village","A Devil Fruit","A Zanpakuto"]]],
"Demon Slayer":[["Who is the main hero?",["Tanjiro","Zenitsu","Inosuke","Giyu"]],["Who is Tanjiro's sister?",["Nezuko","Kanao","Mitsuri","Shinobu"]],["What breathing style does Tanjiro learn first?",["Water Breathing","Thunder Breathing","Beast Breathing","Mist Breathing"]],["What organization fights demons?",["Demon Slayer Corps","Akatsuki","Soul Society","Hero Association"]],["Who is the Flame Hashira?",["Rengoku","Giyu","Tengen","Sanemi"]],["What happens to demons in sunlight?",["They burn","They heal","They transform","Nothing"]],["Who uses Thunder Breathing?",["Zenitsu","Inosuke","Muichiro","Genya"]],["What weapon do Demon Slayers use?",["Nichirin sword","Zanpakuto","Kunai","Katana made of chakra"]],["Who is the demon king?",["Muzan","Akaza","Doma","Kokushibo"]],["What is Nezuko famous for?",["Fighting while resisting humans","Using a Sharingan","Being a Hashira","Using a Bankai"]]],
"My Hero Academia":[["Who is the main hero student?",["Deku","Bakugo","Todoroki","Iida"]],["What is Deku's Quirk?",["One For All","Explosion","Half-Cold Half-Hot","Engine"]],["Who is the Symbol of Peace?",["All Might","Endeavor","Hawks","Aizawa"]],["Which school do heroes attend?",["UA High","Tokyo Jujutsu High","Ninja Academy","Orange Star High"]],["What is Bakugo's Quirk?",["Explosion","Dark Shadow","Engine","Erasure"]],["What is Todoroki's Quirk?",["Half-Cold Half-Hot","One For All","Hardening","Creation"]],["Who is Class 1-A's homeroom teacher?",["Aizawa","All Might","Present Mic","Nezu"]],["What does Quirk generally mean?",["Superhuman ability","Sword release","Spirit monster","Ninja rank"]],["Who is Deku's childhood rival?",["Bakugo","Kirishima","Shinso","Tamaki"]],["What does Plus Ultra mean?",["Go beyond","Give up","Retreat","Train alone"]]],
"Dragon Ball":[["Who is the main hero?",["Goku","Vegeta","Gohan","Piccolo"]],["What are the magical orbs called?",["Dragon Balls","Chaos Emeralds","Senzu Orbs","Soul Gems"]],["What is Goku's signature attack?",["Kamehameha","Rasengan","Getsuga","Detroit Smash"]],["Who is Goku's Saiyan rival?",["Vegeta","Krillin","Yamcha","Tien"]],["What transformation has golden hair?",["Super Saiyan","Bankai","Sage Mode","Domain Expansion"]],["Who is Goku's son?",["Gohan","Trunks","Broly","Frieza"]],["What restores health in battle?",["Senzu Bean","Ramen","Nichirin","Cursed Energy"]],["Who is a famous fusion partner of Goku?",["Vegeta","Piccolo","Krillin","Frieza"]],["What is Shenron?",["Dragon summoned by the Dragon Balls","Saiyan","Android","Master"]],["What does Goku love almost as much as fighting?",["Food","Politics","School","Treasure"]]],
"Attack on Titan":[["Who is the main protagonist?",["Eren","Levi","Armin","Reiner"]],["What walls protect humanity?",["Maria, Rose, Sina","Alpha, Beta, Gamma","East, West, North","Leaf, Sand, Mist"]],["Who is famous as humanity's strongest soldier?",["Levi","Eren","Armin","Jean"]],["What are the giant enemies called?",["Titans","Hollows","Demons","Nomu"]],["What is Eren's home district?",["Shiganshina","Konoha","Karakura","Musutafu"]],["Who can transform into the Colossal Titan?",["Armin","Jean","Levi","Erwin"]],["What organization explores beyond the walls?",["Survey Corps","Demon Slayer Corps","Akatsuki","Soul Reapers"]],["What is Mikasa known for?",["Elite combat skill","Fire breathing","Devil Fruit","Cursed Technique"]],["Who is Eren's adopted sister?",["Mikasa","Historia","Annie","Sasha"]],["What is the series famous for?",["Titans and mystery","Pirate treasure","Ninja villages","Superhero school"]]]
};
const THEME={
"One Piece":{cls:"onepiece",icon:"☠️",tag:"GRAND LINE",effect:"waves",title:"ONE PIECE",hero:"Monkey D. Luffy",chars:["Luffy","Zoro","Nami","Sanji"],accent:"GOLD / OCEAN"},
"Naruto":{cls:"naruto",icon:"🍃",tag:"SHINOBI WORLD",effect:"chakra",title:"NARUTO",hero:"Naruto Uzumaki",chars:["Naruto","Sasuke","Kakashi","Sakura"],accent:"CHAKRA / FIRE"},
"Bleach":{cls:"bleach",icon:"⚔️",tag:"SOUL SOCIETY",effect:"spirit",title:"BLEACH",hero:"Ichigo Kurosaki",chars:["Ichigo","Rukia","Byakuya","Renji"],accent:"REIATSU / SOUL"},
"Jujutsu Kaisen":{cls:"jjk",icon:"👁️",tag:"CURSED ENERGY",effect:"curse",title:"JUJUTSU KAISEN",hero:"Yuji Itadori",chars:["Yuji","Gojo","Megumi","Sukuna"],accent:"CURSED / VIOLET"},
"Demon Slayer":{cls:"demon",icon:"🔥",tag:"BREATHING STYLE",effect:"embers",title:"DEMON SLAYER",hero:"Tanjiro Kamado",chars:["Tanjiro","Nezuko","Zenitsu","Inosuke"],accent:"FLAME / WATER"},
"My Hero Academia":{cls:"mha",icon:"💥",tag:"PLUS ULTRA",effect:"impact",title:"MY HERO ACADEMIA",hero:"Izuku Midoriya",chars:["Deku","Bakugo","Todoroki","All Might"],accent:"HERO / IMPACT"},
"Dragon Ball":{cls:"db",icon:"🐉",tag:"POWER LEVEL",effect:"energy",title:"DRAGON BALL",hero:"Son Goku",chars:["Goku","Vegeta","Gohan","Piccolo"],accent:"KI / SAIYAN"},
"Attack on Titan":{cls:"aot",icon:"🪽",tag:"WALLS FALL",effect:"rumble",title:"ATTACK ON TITAN",hero:"Eren Yeager",chars:["Eren","Mikasa","Levi","Armin"],accent:"RUMBLE / SCOUT"}
};
const IMG={anime:""};
const API=window.ANIME_API_URL||"";
const app={d:{},
esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))},
home(){history.replaceState({}, "", location.pathname);this.renderHome()},poster(t,label){return `<div class="anime-poster ${t.cls}">
<div class="poster-bg"></div><div class="poster-glow glow-1"></div><div class="poster-glow glow-2"></div>
<div class="poster-top"><span>${t.icon} ${this.esc(t.tag)}</span><b>${this.esc(label)}</b></div>
<div class="poster-hero"><div class="character-halo"></div><div class="character-mark">${t.icon}</div><strong>${this.esc(t.hero)}</strong><small>MAIN CHARACTER</small></div>
<div class="poster-title"><small>${this.esc(t.accent)}</small><b>${this.esc(t.title)}</b></div>
<div class="poster-glass">${t.chars.map(c=>`<span>${this.esc(c)}</span>`).join("")}</div>
</div>`},
async init(){const id=new URLSearchParams(location.search).get("challenge");id?await this.join(id):this.renderHome()},
renderHome(){document.body.className="";document.querySelector("#app").innerHTML=`
<section class="hero home-hero">
<div class="eyebrow">✦ LIQUID GLASS ANIME BATTLE</div>
<div class="home-poster">
  <div class="poster-orbit orbit-a"></div><div class="poster-orbit orbit-b"></div>
  <div class="poster-copy"><span>YOUR BATTLEFIELD</span><b>ANIME<br><em>BATTLE</em></b><small>Choose an anime. Enter its world.</small></div>
  <div class="poster-silhouette"><i>⚔</i><i>☄</i><i>🔥</i></div>
  <div class="glass-float glass-float-a">✦ 8 WORLDS</div>
  <div class="glass-float glass-float-b">10 ROUNDS</div>
</div>
<h1>ANIME <em>BATTLE</em></h1>
<p>Every anime gets its own poster, character lineup, typography, colors and battle animation.</p>
<div class="actions"><button class="btn" onclick="app.create()">CREATE CHALLENGE</button><button class="btn secondary" onclick="app.joinForm()">JOIN CHALLENGE</button></div>
</section>
<section class="card anime-showcase"><div class="showcase-head"><span>EXPLORE THE WORLDS</span><small>Tap a poster to start</small></div>
<div class="poster-grid">${Object.entries(THEME).map(([a,t])=>`<button class="mini-poster ${t.cls}" onclick="app.selectAnime('${this.esc(a)}')"><div class="mini-aura"></div><div class="mini-icon">${t.icon}</div><strong>${this.esc(t.title)}</strong><small>${this.esc(t.hero)}</small><div class="mini-chars">${t.chars.map(c=>`<span>${this.esc(c)}</span>`).join("")}</div></button>`).join("")}</div></section>`},
create(){document.querySelector("#app").innerHTML=`<section class="shell"><div class="card"><h2>Choose your anime</h2><p class="sub">Select one anime. The next 10 questions will be only about that anime.</p>${Object.entries(GROUPS).map(([g,list])=>`<div class="field"><label>${g}</label><div class="anime-options">${list.map(a=>`<button class="anime-option" onclick="app.selectAnime('${this.esc(a)}')"><span>⚡</span><strong>${this.esc(a)}</strong><small>10 questions</small></button>`).join("")}</div></div>`).join("")}</div></section>`},
selectAnime(anime){this.d.anime=anime;document.body.className=THEME[anime]?.cls||"";document.querySelector("#app").innerHTML=`<section class="shell"><div class="card"><div class="eyebrow">${this.esc(anime.toUpperCase())}</div><h2>Create ${this.esc(anime)} Battle</h2><p class="sub">Friends who join this link will automatically receive the ${this.esc(anime)} question set.</p><div class="field"><label>YOUR NAME / NICKNAME</label><input id="name" class="input" maxlength="24" placeholder="e.g. Dhanush"></div><div class="field"><label>CHALLENGE TITLE</label><input id="title" class="input" maxlength="55" value="How well do you know ${this.esc(anime)}?"></div><button class="btn" onclick="app.beginCreator()">START ${this.esc(anime.toUpperCase())} BATTLE →</button></div></section>`},
beginCreator(){document.body.className=THEME[this.d.anime]?.cls||"";const n=document.querySelector("#name").value.trim();if(!n)return alert("Enter your name first.");this.d={...this.d,name:n,title:document.querySelector("#title").value.trim(),answers:[]};this.ask(0)},
ask(i){const t=THEME[this.d.anime]||THEME["One Piece"];const q=A[this.d.anime][i];document.body.className=t.cls;document.querySelector("#app").innerHTML=`<section class="shell"><div class="card"><div class="qnum">${this.esc(this.d.anime.toUpperCase())} · QUESTION ${i+1} / 10</div><div class="progress"><i style="width:${i/10*100}%"></i></div><div class="question-media anime-stage"><div class="poster-wrap">${this.poster(t,"ROUND "+(i+1))}</div><div class="energy energy-${t.effect}"></div></div><div class="question">${this.esc(q[0])}</div><div class="answers">${q[1].map((x,j)=>`<div class="answer" style="animation-delay:${j*45}ms" onclick="app.pick(${i},${j})">${this.esc(x)}</div>`).join("")}</div><p class="sub">Only ${this.esc(this.d.anime)} questions in this battle.</p></div></section>`},
pick(i,j){this.d.answers[i]=j;setTimeout(()=>i+1<10?this.ask(i+1):this.doneCreator(),180)},
async doneCreator(){try{const r=await fetch(API+"/api/challenges",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:this.d.name,title:this.d.title,anime:this.d.anime,answers:this.d.answers})});if(!r.ok)throw 1;const x=await r.json();this.d.id=x.id;const url=location.href.split("?")[0]+"?challenge="+encodeURIComponent(x.id);document.querySelector("#app").innerHTML=`<section class="shell"><div class="card score"><div class="eyebrow">⚡ ${this.esc(this.d.anime.toUpperCase())} CHALLENGE READY</div><h2>Battle link created.</h2><p class="sub">Send this link. Your friend will automatically get the same ${this.esc(this.d.anime)} quiz.</p><div class="share"><input id="link" class="input" readonly value="${url}"><button class="btn" style="width:auto" onclick="app.copy()">COPY</button></div><div style="height:10px"></div><button class="btn secondary" onclick="app.share()">SHARE WITH FRIENDS</button><div style="height:10px"></div><button class="btn secondary" onclick="app.home()">BACK HOME</button></div></section>`}catch(e){alert("Backend not connected. Please check Koyeb.")}},
joinForm(){document.querySelector("#app").innerHTML=`<section class="shell"><div class="card"><h2>Join a challenge</h2><p class="sub">Paste your friend's Anime Battle link.</p><div class="field"><input id="joinurl" class="input" placeholder="https://your-site.com/?challenge=..."></div><button class="btn" onclick="app.openJoin()">JOIN →</button></div></section>`},
openJoin(){try{const u=new URL(document.querySelector("#joinurl").value.trim());const id=u.searchParams.get("challenge");if(!id)throw 1;location.href="?challenge="+encodeURIComponent(id)}catch(e){alert("That challenge link is not valid.")}},
async join(id){try{const r=await fetch(API+"/api/challenges/"+encodeURIComponent(id));if(!r.ok)throw 1;const x=await r.json();this.d={id:x.id,name:x.creator,title:x.title,anime:x.anime,answers:[]};if(!A[this.d.anime])throw 1;document.querySelector("#app").innerHTML=`<section class="shell"><div class="card"><div class="eyebrow">⚔️ ${this.esc(this.d.anime.toUpperCase())} CHALLENGE</div><h2>${this.esc(x.creator)} challenged you.</h2><p class="sub">${this.esc(x.title)}</p><div class="field"><label>YOUR NAME / NICKNAME</label><input id="friend" class="input" placeholder="Your name"></div><button class="btn" onclick="app.beginFriend()">ACCEPT ${this.esc(this.d.anime.toUpperCase())} BATTLE →</button></div></section>`}catch(e){document.querySelector("#app").innerHTML=`<section class="shell"><div class="card"><h2>Challenge unavailable</h2><p class="sub">This challenge does not exist, uses an old unsupported anime, or the backend is offline.</p><button class="btn" onclick="app.home()">GO HOME</button></div></section>`}},
beginFriend(){document.body.className=THEME[this.d.anime]?.cls||"";const n=document.querySelector("#friend").value.trim();if(!n)return alert("Enter your name.");this.d.friend=n;this.askFriend(0)},
askFriend(i){const t=THEME[this.d.anime]||THEME["One Piece"];const q=A[this.d.anime][i];document.body.className=t.cls;document.querySelector("#app").innerHTML=`<section class="shell"><div class="card"><div class="qnum">${this.esc(this.d.anime.toUpperCase())} · QUESTION ${i+1} / 10</div><div class="progress"><i style="width:${i/10*100}%"></i></div><div class="question-media anime-stage"><div class="poster-wrap">${this.poster(t,"VISUAL ROUND")}</div><div class="energy energy-${t.effect}"></div></div><div class="question">${this.esc(q[0])}</div><div class="answers">${q[1].map((x,j)=>`<div class="answer" style="animation-delay:${j*45}ms" onclick="app.pickFriend(${i},${j})">${this.esc(x)}</div>`).join("")}</div></div></section>`},
pickFriend(i,j){this.d.answers[i]=j;setTimeout(()=>i+1<10?this.askFriend(i+1):this.finish(),180)},
async finish(){try{const r=await fetch(API+"/api/challenges/"+encodeURIComponent(this.d.id)+"/answer-key");if(!r.ok)throw 1;const x=await r.json();const score=this.d.answers.reduce((s,a,i)=>s+(a===x.answers[i]?1:0),0);const pct=Math.round(score/10*100);const rank=pct>=90?"ANIME SOULMATE":pct>=70?"CERTIFIED SENPAI":pct>=50?"ARC PARTICIPANT":"CASUAL WATCHER";await fetch(API+"/api/challenges/"+encodeURIComponent(this.d.id)+"/results",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:this.d.friend,score,total:10})});document.querySelector("#app").innerHTML=`<section class="shell"><div class="card score"><div class="eyebrow">BATTLE COMPLETE ⚡</div><div class="ring" style="--pct:${pct}%"><div><div class="big">${score}/10</div><small>${this.esc(this.d.anime)}</small></div></div><div class="rank">${rank}</div><p class="sub">You matched ${pct}% of ${this.esc(this.d.name)}'s ${this.esc(this.d.anime)} answers.</p><button class="btn" onclick="app.shareResult()">SHARE MY SCORE</button><div style="height:10px"></div><button class="btn secondary" onclick="app.leaderboard()">VIEW LEADERBOARD</button></div></section>`}catch(e){alert("Could not submit the result. Please try again.")}},
async leaderboard(){try{const r=await fetch(API+"/api/challenges/"+encodeURIComponent(this.d.id)+"/leaderboard");if(!r.ok)throw 1;const list=(await r.json()).leaderboard||[];document.querySelector("#app").innerHTML=`<section class="shell"><div class="card"><div class="eyebrow">🏆 ${this.esc(this.d.anime.toUpperCase())} RANKINGS</div><h2>Who knows ${this.esc(this.d.name)} best?</h2>${list.length?list.map((x,i)=>`<div class="row"><span class="num">#${i+1}</span><strong>${this.esc(x.name)}</strong><span class="pill">${x.score}/${x.total}</span></div>`).join(""):"<p class='sub'>No scores yet.</p>"}<div style="height:18px"></div><button class="btn secondary" onclick="app.home()">CREATE YOUR OWN</button></div></section>`}catch(e){alert("Leaderboard is unavailable.")}},
async copy(){await navigator.clipboard.writeText(document.querySelector("#link").value);alert("Challenge link copied!")},async share(){const u=document.querySelector("#link").value;if(navigator.share)await navigator.share({title:"Anime Battle",text:"Can you beat my anime score? ⚔️",url:u});else this.copy()},async shareResult(){const t="I just took an Anime Battle ⚔️ Can you beat my score?";if(navigator.share)await navigator.share({title:"Anime Battle",text:t,url:location.href});else{await navigator.clipboard.writeText(t+" "+location.href);alert("Share text copied!")}}
};
app.init();